Feature
madinkum/portfolio pull request #1
Opened 2023-07-17 10:16 UTC by madinkum

learning how to use branches

2023-07-22 12:43 UTC, geekmidas requested changes

2023-07-22 12:43 UTC, geekmidas commented on style.css
> +    width:55%;
Does this not affect responsiveness?

2023-07-22 12:43 UTC, geekmidas commented on skills.html
> +                        <span class="percent">55%</span>
55% are you sure? 😄

2023-07-24 07:58 UTC, madinkum commented on style.css
> +    width:55%;
No , it does not affect the responsiveness.

2023-08-07 07:29 UTC, merged